### PR TITLE
Allow the player to go back to the main menu.

### PR DESCRIPTION
**Pull request by szabopeter**

### CODE REVIEW

**Comment by rodrigets** [comment]
Hi @szabopeter 

Please update your repository, this is conflict in the merge.
Use git rebase in the master.
Thank you

**Comment by szabopeter** [comment]
Was there any specific reason for not merging this?

**Comment by rodrigets** [comment]
Hi @szabopeter

Please update your repository, this is conflict in the merge.
Use git rebase in the master.
Thank you.

It was conflicting, I sent you the message above and I thought I would not look.
You can verify?
If so, I reopen the PR.

**Comment by szabopeter** [comment]
I rebased a few days ago, the network graph shows this:
image

**Comment by rodrigets** [comment]
@szabopeter ,
He had not checked his pass.
Now it's correct.
Sorry for the inconvenience.

**Comment by szabopeter** [comment]
No problem at all.

**Pull request merged**
